// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0hNINSJG3IShlMVKrTiOcLLdv_GtW4M',
    appId: '1:892454872083:web:0a50981d7842c9e3cd0be6',
    messagingSenderId: '892454872083',
    projectId: 'betalyze-eaf05',
    authDomain: 'betalyze-eaf05.firebaseapp.com',
    storageBucket: 'betalyze-eaf05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5_0qBY8Agr3WBAOqP-4akx70m3P1MGUw',
    appId: '1:892454872083:android:d6c137836e6bcb4dcd0be6',
    messagingSenderId: '892454872083',
    projectId: 'betalyze-eaf05',
    storageBucket: 'betalyze-eaf05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVcj3qRQqEvh4gi2U4hOpz8qUCxaErBA',
    appId: '1:892454872083:ios:0abb15545d5b0f61cd0be6',
    messagingSenderId: '892454872083',
    projectId: 'betalyze-eaf05',
    storageBucket: 'betalyze-eaf05.firebasestorage.app',
    iosBundleId: 'com.example.betalyzeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVcj3qRQqEvh4gi2U4hOpz8qUCxaErBA',
    appId: '1:892454872083:ios:0abb15545d5b0f61cd0be6',
    messagingSenderId: '892454872083',
    projectId: 'betalyze-eaf05',
    storageBucket: 'betalyze-eaf05.firebasestorage.app',
    iosBundleId: 'com.example.betalyzeMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT0hNINSJG3IShlMVKrTiOcLLdv_GtW4M',
    appId: '1:892454872083:web:e362099a74d577a4cd0be6',
    messagingSenderId: '892454872083',
    projectId: 'betalyze-eaf05',
    authDomain: 'betalyze-eaf05.firebaseapp.com',
    storageBucket: 'betalyze-eaf05.firebasestorage.app',
  );
}
